  export const topicTags = {
    "Web Development": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Angular",
      "Vue.js",
      "Next.js",
      "SEO",
      "Web Performance",
      "Responsive Design",
    ],
    "App Development": [
      "Android",
      "iOS",
      "Flutter",
      "React Native",
      "Kotlin",
      "Swift",
      "Cross-platform",
      "App Design",
      "User Testing",
    ],
    "AI/ML": [
      "Machine Learning",
      "Deep Learning",
      "Python",
      "TensorFlow",
      "PyTorch",
      "Data Preprocessing",
      "NLP",
      "Computer Vision",
      "Model Training",
    ],
    "Cyber Security": [
      "Penetration Testing",
      "Ethical Hacking",
      "Network Security",
      "Encryption",
      "Firewalls",
      "Malware Analysis",
      "Incident Response",
    ],
    "Cloud Computing": [
      "AWS",
      "Azure",
      "Google Cloud",
      "Serverless",
      "Kubernetes",
      "Cloud Storage",
      "DevOps",
      "Scalability",
      "CDN",
    ],
    "Data Science": [
      "Python",
      "R",
      "Data Visualization",
      "Pandas",
      "Numpy",
      "Statistics",
      "EDA",
      "Big Data",
      "Data Cleaning",
    ],
    DevOps: [
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Monitoring",
      "Infrastructure as Code",
      "SRE",
      "GitOps",
    ],
    Blockchain: [
      "Smart Contracts",
      "Ethereum",
      "DeFi",
      "Cryptocurrency",
      "Solidity",
      "Web3.js",
      "dApps",
      "Consensus Mechanisms",
    ],
    "Internet of Things (IoT)": [
      "Sensors",
      "Arduino",
      "Raspberry Pi",
      "MQTT",
      "Edge Computing",
      "IoT Security",
      "Smart Devices",
      "Home Automation",
    ],
    "UI/UX Design": [
      "Wireframing",
      "User Research",
      "Interaction Design",
      "Figma",
      "Sketch",
      "Adobe XD",
      "Accessibility",
      "Usability",
      "Design Systems",
    ],
  };
